### ISSUE TITLE
System dependencies as build options/arguments

### ISSUE THREAD

**Issue by psolymos** [analythium/openfaas-rstats-templates#10]
System dependencies should be added to the YAML file as [build option](https://docs.openfaas.com/cli/build/#10-apply-build-options) 
or passed as [build argument](https://docs.openfaas.com/cli/build/#30-pass-custom-build-arguments).

For this, add `ADDITIONAL_PACKAGE` `ARG` to the Dockerfile.

https://docs.openfaas.com/cli/build/#10-apply-build-options

**Comment by psolymos** [comment]
Decided to go with the build argument in the README file, but as the docs say, it is less preferred when e.g. multiple functions are described in the same stack YAML file.

When going the build option route, here is the recipe:

edit the `/templates/<template-name>/template.yml` file:

```
language: rstats
fprocess: Rscript index.R
build_options:
  - name: dev
    packages:
      - git-core
      - libssl-dev
      - libcurl4-gnutls-dev
```

Then call `faas-cli new` then

```
faas-cli up -f hello-rstats.yml --build-option dev
```
**Note:** both _build options_ and _build arguments_ have been tested and are working as expected: installing system dependency packages during build.
